### PR TITLE
make the gateway NOT hang when the receiver crash

### PR DESCRIPTION
**Pull request by siscia**
the gateway relies on reading data from the receiver in order to
return controll to the main thread.

When everything goes right, the gateway reads the correct amount of
data from the pipe and exit.
When the receiver crash, for whatever reason, the data is not
present in the pipe. Moreover the pipe is not closed automatically
by the OS, since the File Descriptors are still open and managed by
the gateway itself.

This commit close the FDs on the gateway side, so that when the
receiver crash, no more FDs are open on the socket and the read
call can be unblocked by EOF.

### CODE REVIEW

**Comment by jblomer** [comment]
Good catch!  Now, the tricky part is how to test it.  I think we should add a little bit of extra code to the receiver, such that if, for example, a certain environment variable is set, the receiver would self-destruct.

**Comment by siscia** [comment]
I was thinking to add a command to the receiver, like a specific objectpack type that will kill itself.

But I like also the idea of an environmental variable as well.

At the moment we already deploy it on unpack so if that stay stable for enough time is already a good indication...

**Comment by siscia** [comment]
Implemented this solution for unittest.

As soon as https://github.com/cvmfs/cvmfs/pull/2551 get merged I will merge this as well.

**Comment by siscia** [comment]
This can be merged, modulo CI

**Review by jblomer — APPROVED** [review]

**Pull request merged**
